#pragma once
#define SYS_read            0
#define SYS_write           1
#define SYS_open            2
#define SYS_close           3
#define SYS_stat            4
#define SYS_fstat           5
#define SYS_lseek           8
#define SYS_mmap            9
#define SYS_munmap          11
#define SYS_rt_sigaction    13
#define SYS_rt_sigprocmsk   14
#define SYS_ioctl           16
#define SYS_access          21
#define SYS_dup             32
#define SYS_getpid          39
#define SYS_clone           56
#define SYS_execve          59
#define SYS_exit            60
#define SYS_wait4           61
#define SYS_uname           63
#define SYS_getuid          102
#define SYS_getgid          104
#define SYS_geteuid         107
#define SYS_getegid         108
#define SYS_getppid         110
#define SYS_getpgid         121
#define SYS_arch_prctl      158
#define SYS_gettid          186
#define SYS_futex           202
#define SYS_getdents64      217
#define SYS_clock_gettime   228
#define SYS_newfstatat      262